version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bootcamp-product-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t0bd48f8av1y"
s3_prefix = "bootcamp-product-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
